version: '3.9'

services:
  server:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: lgsus
      POSTGRES_DB: eps
    volumes:
      - data:/var/lib/postgresql/data
      - './scripts/:/docker-entrypoint-initdb.d/:ro'
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    depends_on:
      - default

volumes:
  data:
